server:
  port: 8888
  servlet:
    context-path: /demo
mybatis:
  type-aliases-package: club.banyuan.entity
  mapper-locations: classpath:club/banyuan/mapper/*Mapper.xml
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework?&useSSL=false&serverTimezone=UTC
    username: root
    password: yxc.9894