server:
  port: 8081
custom:
  username: 歪比歪比
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: yxc.9894
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    club.banyuan: debug
spring:
  redis:
    database: 0 # 数据库索引 默认0
    host: 127.0.0.1
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        max-idle: 2 # 连接池中的最大空闲连接 默认8
        min-idle: 2 # 连接池中的最小空闲连接 默认0
        max-active: 2 # 连接池最大连接数 默认8 ，负数表示没有限制
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1